### ISSUE TITLE
Does the -v or --version flag print the tool's name and version? 

### ISSUE THREAD

**Issue by MizuhoOkimoto** [aserputov/final-qck-ssg#3]
![image](https://user-images.githubusercontent.com/54873998/133850406-fcdadbd1-1bfb-4f7c-bdf7-a1bf45ad63d9.png)
This project requires your tool’s name, and only --version worked for me.

**Comment by aserputov** [comment]
Hello, MizuhoOkimoto, yes I fixed that issue with code below.
.version("v", "version", "qck-ssg v0.1.2")
  .alias("v", "version")
