### ISSUE TITLE
Make detailed suggestions?

### ISSUE THREAD

**Issue by MizuhoOkimoto** [aserputov/final-qck-ssg#5]
- Is it possible not to display the warning on the command line?
- Is it possible not to make index.html? Or do you intentionally generate it as well?
-  You made it console.log('File is created successfully.') as a memo, but I think it would be better to keep it, and people could check if the file was generated correctly on the command line.

**Comment by aserputov** [comment]
1. Can you please provide more about this error ?
2. I will correct this feature.
3. Fixed. Returned it back.

**Comment by MizuhoOkimoto** [comment]
> 1. Can you please provide more about this error ?
> 2. I will correct this feature.
> 3. Fixed. Returned it back.

The warning is "(node:16300) ExperimentalWarning: The ESM module loader is experimental." Is it possible to get rid of it?
